---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: test/integration/default/data_bags
    run_list:
      - recipe[omnitruck::default]
    attributes:
      applications:
        omnitruck: 873/20170420131452
